import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics Textbook
  textbookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/index',
        'module-1/introduction-to-ros2',
        'module-1/ros2-architecture',
        'module-1/nodes-communication',
        'module-1/packages-workspaces',
        'module-1/tools-debugging',
        'module-1/ros2-humanoid-robotics',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/index',
        'module-2/introduction-to-digital-twins',
        'module-2/gazebo-environment',
        'module-2/robot-modeling',
        'module-2/unity-integration',
        'module-2/physics-dynamics',
        'module-2/simulation-reality-transfer',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3/index',
        'module-3/introduction-to-isaac',
        'module-3/isaac-ros-gems',
        'module-3/perception-systems',
        'module-3/planning-navigation',
        'module-3/ai-model-deployment',
        'module-3/isaac-sim-integration',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/index',
        'module-4/introduction-to-vla',
        // Additional module 4 topics will be added here
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Weekly Breakdown (Weeks 1-13)',
      items: [
        'weekly-breakdown/index',
        'weekly-breakdown/week-1',
        'weekly-breakdown/week-2',
        'weekly-breakdown/week-3',
        'weekly-breakdown/week-4',
        'weekly-breakdown/week-5',
        'weekly-breakdown/week-6',
        'weekly-breakdown/week-7',
        'weekly-breakdown/week-8',
        'weekly-breakdown/week-9',
        'weekly-breakdown/week-10',
        'weekly-breakdown/week-11',
        'weekly-breakdown/week-12',
        'weekly-breakdown/week-13',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Assessments & Evaluations',
      items: [
        'assessments/index',
        'assessments/module-1-assessment',
        'assessments/module-2-assessment',
        'assessments/module-3-assessment',
        'assessments/module-4-assessment',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Hardware Requirements',
      items: [
        'hardware-requirements/index',
        'hardware-requirements/hardware-setup-guide',
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
