import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics Textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/index',
        'module-1/ros2-architecture',
        'module-1/ros2-humanoid-robotics',
        'module-1/nodes-communication',
        'module-1/packages-workspaces',
        'module-1/tools-debugging',
        'module-1/bridging-python-ros',
        'module-1/urdf-humanoids',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/index',
        'module-2/introduction-to-digital-twins',
        'module-2/gazebo-environment',
        'module-2/urdf-sdf-formats',
        'module-2/sensor-simulation',
        'module-2/physics-dynamics',
        'module-2/simulation-reality-transfer',
        'module-2/unity-integration',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3/index',
        'module-3/introduction-to-isaac',
        'module-3/isaac-sim-integration',
        'module-3/isaac-ros-gems',
        'module-3/perception-systems',
        'module-3/planning-navigation',
        'module-3/reinforcement-learning',
        'module-3/sim-transfer-techniques',
        'module-3/ai-model-deployment',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Models',
      items: [
        'module-4/index',
        'module-4/introduction-to-vla',
        'module-4/multimodal-perception',
        'module-4/cognitive-planning',
        'module-4/voice-to-action',
        'module-4/simulation-reality-transfer',
        'module-4/capstone-project',
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
